### ISSUE TITLE
Add a copy to clipboard function among the share buttons

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#110]
**Is your feature request related to a problem? Please describe.**
We want a quick way to access an article link alias. Currently, we have to "share" it somewhere with the share buttons, copy the link and then abort the sharing.

**Describe the solution you'd like**
We want a button to copy to clipboard the permanent URL (alias), placed just next to the social media share buttons here:

![image](https://user-images.githubusercontent.com/50109671/109801639-097dc580-7c1f-11eb-8610-4631d250c670.png)

This should be similar to the copy button in the codeblocks.

**Comment by heyarviind** [comment]
I can see you have already added the shareable link with the share icons... should I add copy icons too? the link you added is hidden in the mobile view

**Comment by andreantonacci** [comment]
@heyarviind Hi Arvind, yes please! I added the shareable link as a temporary solution because I could not make it work as a button (I don't know how to copy to clipboard in JS). And I hid the link from mobile only because it would be too long to display.

However, when you'll add the copy to clipboard icon (like the one in the codeblock), you can remove my temporary shareable link solution on the right. Just make sure to use the same "algorithm". It uses the first available alias specified in the front matter. If no aliases are specified, then the sharing should be hidden. I guess it's similar to how it's done now. Thanks!

**Comment by heyarviind** [comment]
Alright, thanks

**Comment by andreantonacci** [comment]
Is this done yet? I see the new button, but if I click on it, it does nothing. Also, my temporary link box on the right is still there.

Please, use a different icon for the copy button. Your icon is outline only, while all the other share buttons have solid icons. Use a solid icon for the copy button too, like this one: https://thenounproject.com/search/?q=copy&i=3399366 
Similar to other ones, it should be blue and orange only on hover, thanks.

**Comment by heyarviind** [comment]
Sure, it is not done yet... I will work on it

**Comment by andreantonacci** [comment]
Great job, thanks. Can you please vertically align the icons on mobile? Their center point (red line) doesn't match the "Share" text center line. They seem aligned by their top edge. We want them align their centers instead, thanks

![IMG_2E773579FDEA-1](https://user-images.githubusercontent.com/50109671/114849270-e0d11a00-9ddf-11eb-95d5-8a43b7a671d8.jpeg)

**Comment by heyarviind** [comment]
fixed it, which tool are you using to check this btw?

**Comment by andreantonacci** [comment]
Just my eyes 😬

**Comment by andreantonacci** [comment]
Are you sure it's fixed? I cleared the cache but I still see them below the center line:

![IMG_F53E13D683ED-1](https://user-images.githubusercontent.com/50109671/114997643-5b616e80-9ea0-11eb-831d-d410c6d8671f.jpeg)

For a comparison, here's the same test on the desktop page. See how here the icons are a bit higher and lie perfectly on the line. The facebook icon seems cut perfectly in half.

![Screenshot 2021-04-16 at 10 40 09](https://user-images.githubusercontent.com/50109671/114997775-7e8c1e00-9ea0-11eb-893c-d95ed434de4c.png)

**Comment by andreantonacci** [comment]
Looks better, thanks
